EMOTE_STRIKEOUT = "K"
EMOTE_STRIKEOUT_LOOKING = "ꓘ"
EMOTE_RBI = ":D"
EMOTE_EARNED_RUN = ":)"
# Timezone
BOT_TIMEZONE = 'US/Eastern'

EMOTE_UNEARNED_RUN = "¯\_(ツ)_/¯"
EMOTE_HOMERUN = ":heart_eyes_cat:"
EMOTE_GRAND_SLAM = ":scream_cat:"

# Game Status Constants
NO_GAME_STATUS_TITLE = "No Game Today"
NO_GAME_STATUS_DESCRIPTION = "Take a day off, relax :)"
NO_GAME_STATUS_BODY = ""

SCHEDULED_GAME_STATUS_TITLE = "We've got a game today"
SCHEDULED_GAME_STATUS_BODY = ""

PREGAME_TITLE = "PREGAME_STATUS_TITLE"
PREGAME_DESCRIPTION = "PREGAME_STATUS_DESCRIPTION"
PREGAME_BODY = "PREGAME_STATUS_BODY"

WARMUP_TITLE = 'Game\'s about to start, everyone get in here!'
WARMUP_BODY = "" 

GAMESTARTED_TITLE = 'Play ball!'
GAMESTARTED_DESCRIPTION = 'HYPE HYPE HYPE HYPE HYPE HYPE HYPE'
GAMESTARTED_BODY = ""

RAINDELAY_TITLE = "Rain Delay"
RAINDELAY_DESCRIPTION = "Game is currently in rain delay"
RAINDELAY_BODY = "Rain rain, go away.  Come on back another day."

COMPLETEDEARLYRAIN_TITLE = "COMPLETED_EARLY_RAIN_PLACEHOLDER_TITLE"
COMPLETEDEARLYRAIN_DESCRIPTION = "COMPLETED_EARLY_RAIN_STATUS_PLACEHOLDER_DESCRIPTION"
COMPLETEDEARLYRAIN_BODY = "COMPLETED_EARLY_RAIN_STATUS_PLACEHOLDER_BODY"

POSTPONED_TITLE = "{} Game Postponed"
POSTPONED_DESCRIPTION = "Game's over, makeup to be played later"
POSTPONED_BODY = "On the bright side, we didn't lose"

GAMEOVER_TITLE = "GAMEOVER_STATUS_PLACEHOLDER_TITLE"
GAMEOVER_DESCRIPTION = "GAMEOVER_STATUS_PLACEHOLDER_DESCRIPTION"
GAMEOVER_BODY = "GAMEOVER_STATUS_PLACEHOLDER_BODY"

FINAL_TITLE = "FINAL_STATUS_PLACEHOLDER_TITLE"
FINAL_DESCRIPTION = "FINAL_STATUS_PLACEHOLDER_DESCRIPTION"
FINAL_BODY = "FINAL_STATUS_PLACEHOLDER_BODY"

GAMEOVERTIED_TITLE = "GAME_OVER_TIED_STATUS_PLACEHOLDER_TITLE"
GAMEOVERTIED_DESCRIPTION = "GAME_OVER_TIED_STATUS_PLACEHOLDER_DESCRIPTION"
GAMEOVERTIED_BODY = "GAME_OVER_TIED_STATUS_PLACEHOLDER_BODY"

FINALTIED_TITLE = "FINAL_TIED_STATUS_PLACEHOLDER_TITLE"
FINALTIED_DESCRIPTION = "FINAL_TIED_STATUS_PLACEHOLDER_DESCRIPTION"
FINALTIED_BODY = "FINAL_TIED_STATUS_PLACEHOLDER_BODY"

SEVENTH_INNING_STRETCH = "SEVENTH_INNING_STRETCH_PLACEHOLDER"
