# Game Status Constants
SCHEDULED_TITLE = "SCHEDULED_GAME_STATUS_TITLE"
SCHEDULED_DESCRIPTION = "SCHEDULED_GAME_STATUS_DESCRIPTION"
SCHEDULED_BODY = "SCHEDULED_GAME_STATUS_BODY"

PREGAME_TITLE = "PREGAME_STATUS_TITLE"
PREGAME_DESCRIPTION = "PREGAME_STATUS_DESCRIPTION"
PREGAME_BODY = "PREGAME_STATUS_BODY"

WARMUP_TITLE = "WARMUP_STATUS_TITLE"
WARMUP_DESCRIPTION = "WARMUP_STATUS_DESCRIPTION"
WARMUP_BODY = "WARMUP_STATUS_BODY"

GAMESTARTED_TITLE = "GAMESTARTED_STATUS_TITLE"
GAMESTARTED_DESCRIPTION = "GAMESTARTED_STATUS_DESCRIPTION"
GAMESTARTED_BODY = "GAMESTARTED_STATUS_BODY"

RAINDELAY_TITLE = "RAIN_DELAY_STATUS_PLACEHOLDER_TITLE"
RAINDELAY_DESCRIPTION = "RAIN_DELAY_STATUS_PLACEHOLDER_DESCRIPTION"
RAINDELAY_BODY = "RAIN_DELAY_STATUS_PLACEHOLDER_BODY"

COMPLETEDEARLYRAIN_TITLE = "COMPLETED_EARLY_RAIN_PLACEHOLDER_TITLE"
COMPLETEDEARLYRAIN_DESCRIPTION = "COMPLETED_EARLY_RAIN_STATUS_PLACEHOLDER_DESCRIPTION"
COMPLETEDEARLYRAIN_BODY = "COMPLETED_EARLY_RAIN_STATUS_PLACEHOLDER_BODY"

POSTPONED_TITLE = "POSTPONED_STATUS_PLACEHOLDER_TITLE"
POSTPONED_DESCRIPTION = "POSTPONED_STATUS_PLACEHOLDER_DESCRIPTION"
POSTPONED_BODY = "POSTPONED_STATUS_PLACEHOLDER_BODY"

GAMEOVER_TITLE = "GAMEOVER_STATUS_PLACEHOLDER_TITLE"
GAMEOVER_DESCRIPTION = "GAMEOVER_STATUS_PLACEHOLDER_DESCRIPTION"
GAMEOVER_BODY = "GAMEOVER_STATUS_PLACEHOLDER_BODY"

FINAL_TITLE = "FINAL_STATUS_PLACEHOLDER_TITLE"
FINAL_DESCRIPTION = "FINAL_STATUS_PLACEHOLDER_DESCRIPTION"
FINAL_BODY = "FINAL_STATUS_PLACEHOLDER_BODY"

GAMEOVERTIED_TITLE = "GAME_OVER_TIED_STATUS_PLACEHOLDER_TITLE"
GAMEOVERTIED_DESCRIPTION = "GAME_OVER_TIED_STATUS_PLACEHOLDER_DESCRIPTION"
GAMEOVERTIED_BODY = "GAME_OVER_TIED_STATUS_PLACEHOLDER_BODY"

FINALTIED_TITLE = "FINAL_TIED_STATUS_PLACEHOLDER_TITLE"
FINALTIED_DESCRIPTION = "FINAL_TIED_STATUS_PLACEHOLDER_DESCRIPTION"
FINALTIED_BODY = "FINAL_TIED_STATUS_PLACEHOLDER_BODY"

SEVENTH_INNING_STRETCH = "SEVENTH_INNING_STRETCH_PLACEHOLDER"
